version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  dailydn.api:
    build:
      context: ./src/DailyDN.API
      dockerfile: Dockerfile
    container_name: dailydn.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=DailyDNDB;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - mssql
    ports:
      - "8080:8080"

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - os_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"   # OpenSearch REST API
      - "9600:9600"   # Performance Analyzer

  graylog:
    image: graylog/graylog:6.0
    container_name: graylog
    environment:
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/config/node-id
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper123456
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongo/graylog
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    depends_on:
      - mongo
      - opensearch
    restart: unless-stopped
    ports:
      - "9000:9000"    # Web UI
      - "12201:12201/udp"  # GELF UDP input
      - "12201:12201/tcp"  # GELF TCP input
    volumes:
      - graylog_data:/usr/share/graylog/data

volumes:
  mongo_data:
  os_data:
  graylog_data:
  mssql_data:
